/**
 * Bilingual UI copy (English / ಕನ್ನಡ) for the CAD operator dashboard.
 * Shown together so users can read either language without a separate toggle.
 */

export const cadBi = {
  layout: {
    logoAlt: "North Cot CAD / ನಾರ್ತ್ ಕಾಟ್ CAD",
    siderBrand: "CAD Center / CAD ಕೇಂದ್ರ",
    menuHome: "Home / ಮುಖಪುಟ",
    menuCurrent: "View Current Projects / ಪ್ರಸ್ತುತ ಯೋಜನೆಗಳು",
    menuHistory: "View Order History / ಆರ್ಡರ್ ಇತಿಹಾಸ",
    menuWallet: "View Wallet / ವಾಲೆಟ್",
    headerTitle: "North Cot CAD Project / ನಾರ್ತ್ ಕಾಟ್ CAD ಯೋಜನೆ",
    logout: "Logout / ಲಾಗೌಟ್",
    expandMenu: "Expand menu / ಮೆನು ವಿಸ್ತರಿಸಿ",
    collapseMenu: "Collapse menu / ಮೆನು ಸಂಕುಚಿಸಿ",
  },
  home: {
    pageTitle: "CAD Center Dashboard / CAD ಕೇಂದ್ರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    editProfile: "Edit Profile / ಪ್ರೊಫೈಲ್ ತಿದ್ದಿ",
    orderStats: "Order Statistics / ಆರ್ಡರ್ ಅಂಕಿಅಂಶಗಳು",
    totalOrders: "Total Orders / ಒಟ್ಟು ಆರ್ಡರ್‌ಗಳು",
    approvedOrders: "Approved Orders / ಅನುಮೋದಿತ ಆರ್ಡರ್‌ಗಳು",
    rejectedOrders: "Rejected Orders / ತಿರಸ್ಕೃತ ಆರ್ಡರ್‌ಗಳು",
    inProgress: "In Progress / ಪ್ರಗತಿಯಲ್ಲಿ",
    pendingNeedChanges: "Pending: {p} · Need changes: {n} / ಬಾಕಿ: {p} · ಬದಲಾವಣೆ: {n}",
    ordersByStatus: "Orders by Status / ಸ್ಥಿತಿಯ ಪ್ರಕಾರ ಆರ್ಡರ್‌ಗಳು",
    statusBreakdown: "Status breakdown / ಸ್ಥಿತಿ ವಿಭಜನೆ",
    completionRate: "Completion rate / ಪೂರ್ಣಗೊಳಿಸುವಿಕೆ ದರ",
    approvedOfTotal: "{a} of {t} orders approved / {t} ರಲ್ಲಿ {a} ಆರ್ಡರ್‌ಗಳು ಅನುಮೋದಿತ",
    chartApproved: "Approved / ಅನುಮೋದಿತ",
    chartPending: "Pending / ಬಾಕಿ",
    chartNeedChanges: "Need changes / ಬದಲಾವಣೆ ಬೇಕು",
    chartRejected: "Rejected / ತಿರಸ್ಕೃತ",
  },
  orders: {
    currentTitle: "View Current Projects / ಪ್ರಸ್ತುತ ಯೋಜನೆಗಳು",
    currentIntro:
      "Survey sketch assignments for your CAD account. Open details to view files, upload CAD deliverables, and see notes. / ನಿಮ್ಮ CAD ಖಾತೆಗೆ ಸರ್ವೇ ಸ್ಕೆಚ್ ನಿಯೋಜನೆಗಳು. ಫೈಲ್‌ಗಳನ್ನು ನೋಡಲು, CAD ಫೈಲ್ ಸಲ್ಲಿಸಲು, ಟಿಪ್ಪಣಿಗಳನ್ನು ನೋಡಲು ವಿವರಗಳನ್ನು ತೆರೆಯಿರಿ.",
    historyTitle: "View Order History / ಆರ್ಡರ್ ಇತಿಹಾಸ",
    historyIntro:
      "All orders (current, completed, and rejected). View details and upload CAD files where applicable. / ಎಲ್ಲಾ ಆರ್ಡರ್‌ಗಳು (ಪ್ರಸ್ತುತ, ಪೂರ್ಣ, ತಿರಸ್ಕೃತ). ಅಗತ್ಯವಿದ್ದಲ್ಲಿ ವಿವರಗಳು ಮತ್ತು CAD ಫೈಲ್ ಅಪ್ಲೋಡ್.",
    slNo: "Sl. No / ಕ್ರ. ಸಂ.",
    orderDate: "Order Date / ಆರ್ಡರ್ ದಿನಾಂಕ",
    orderId: "Order ID / ಆರ್ಡರ್ ಐಡಿ",
    customerName: "Customer Name / ಗ್ರಾಹಕರ ಹೆಸರು",
    phoneCol: "Phone / ಫೋನ್",
    assignedAt: "Assigned at / ನಿಯೋಜಿಸಿದ ಸಮಯ",
    applicationId: "Application ID / ಅರ್ಜಿ ಸಂಖ್ಯೆ",
    dueDate: "Due date / ಕೊನೆ ದಿನಾಂಕ",
    status: "Status / ಸ್ಥಿತಿ",
    details: "Details / ವಿವರಗಳು",
    viewDetails: "View Details / ವಿವರಗಳನ್ನು ನೋಡಿ",
    action: "Action / ಕ್ರಿಯೆ",
    totalOrders: "Total {n} orders / ಒಟ್ಟು {n} ಆರ್ಡರ್‌ಗಳು",
    accept: "Accept / ಸ್ವೀಕರಿಸಿ",
    reject: "Reject / ತಿರಸ್ಕರಿಸಿ",
    uploadDrawing: "Upload Drawing / ಡ್ರಾಯಿಂಗ್ ಅಪ್ಲೋಡ್",
    expired: "Expired / ಅವಧಿ ಮೀರಿದೆ",
    assignmentStatus: {
      ASSIGNED: "Assigned / ನಿಯೋಜಿಸಲಾಗಿದೆ",
      IN_PROGRESS: "In Progress / ಪ್ರಗತಿಯಲ್ಲಿ",
      COMPLETED: "Completed / ಪೂರ್ಣಗೊಂಡಿದೆ",
      ON_HOLD: "On Hold / ನಿಲ್ಲಿಸಲಾಗಿದೆ",
      CANCELLED: "Cancelled / ರದ್ದು",
      PENDING: "Pending / ಬಾಕಿ",
      NEED_CHANGES: "Changes required / ಬದಲಾವಣೆ ಅಗತ್ಯ",
    },
    historyStatus: {
      approved: "Approved / ಅನುಮೋದಿತ",
      rejected: "Rejected / ತಿರಸ್ಕೃತ",
      need_changes: "Need Changes / ಬದಲಾವಣೆ ಬೇಕು",
      pending: "Pending / ಬಾಕಿ",
    },
    loadCurrentFail: "Failed to load current orders / ಪ್ರಸ್ತುತ ಆರ್ಡರ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು ವಿಫಲ",
    loadDetailFail: "Failed to load order details / ಆರ್ಡರ್ ವಿವರ ಲೋಡ್ ವಿಫಲ",
    orderAccepted: "Order accepted / ಆರ್ಡರ್ ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
    orderRejected: "Order rejected / ಆರ್ಡರ್ ತಿರಸ್ಕೃತ",
    updateStatusFail: "Failed to update order status / ಸ್ಥಿತಿ ನವೀಕರಣ ವಿಫಲ",
    acceptWindowWarn:
      "This assignment is older than 2 hours and may have reverted to admin. / ಈ ನಿಯೋಜನೆ 2 ಗಂಟೆಗಿಂತ ಹಳೆಯದು; ಆಡ್ಮಿನ್‌ಗೆ ಹಿಂದಿರುಗಿರಬಹುದು.",
    selectCadFile: "Please select a CAD file to deliver. / ಸಲ್ಲಿಸಲು CAD ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ.",
    cadDelivered: "CAD deliverable submitted successfully / CAD ಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ",
    deliverFail: "Failed to deliver CAD file / CAD ಫೈಲ್ ಸಲ್ಲಿಕೆ ವಿಫಲ",
  },
  drawer: {
    application: "Application / ಅರ್ಜಿ",
    close: "Close / ಮುಚ್ಚಿ",
    uploadCadFiles: "Upload CAD File(s) / CAD ಫೈಲ್(ಗಳು) ಅಪ್ಲೋಡ್",
    assignment: "Assignment / ನಿಯೋಜನೆ",
    surveySketch: "Survey sketch / ಸರ್ವೇ ಸ್ಕೆಚ್",
    surveyor: "Surveyor / ಭೂಮಾಪಕ",
    reviewNote: "Review note / ಪರಿಶೀಲನೆ ಟಿಪ್ಪಣಿ",
    uploadedDocuments: "Uploaded documents / ಅಪ್ಲೋಡ್ ದಾಖಲೆಗಳು",
    singleUpload: "Single upload / ಏಕ ಅಪ್ಲೋಡ್",
    perDocument: "Per document / ಪ್ರತಿ ದಾಖಲೆ",
    otherDocuments: "Other documents / ಇತರ ದಾಖಲೆಗಳು",
    cadDeliverables: "CAD deliverables / CAD ಫೈಲ್‌ಗಳು",
    uploadCadFile: "Upload CAD file / CAD ಫೈಲ್ ಅಪ್ಲೋಡ್",
    uploadCadHelp: "Upload completed CAD drawing files for this application. / ಈ ಅರ್ಜಿಗೆ ಪೂರ್ಣಗೊಂಡ CAD ಡ್ರಾಯಿಂಗ್ ಫೈಲ್‌ಗಳನ್ನು ಅಪ್ಲೋಡ್ ಮಾಡಿ.",
    selectCadFiles: "Select CAD file(s) / CAD ಫೈಲ್(ಗಳು) ಆಯ್ಕೆ",
    filesSelectedHint:
      "{n} file(s) selected. Use \"Upload CAD File(s)\" in the header to submit. / {n} ಫೈಲ್ ಆಯ್ಕೆ. ಸಲ್ಲಿಸಲು ಶೀರ್ಷಿಕೆಯಲ್ಲಿರುವ \"Upload CAD File(s)\" ಬಳಸಿ.",
    applicationId: "Application ID / ಅರ್ಜಿ ಸಂಖ್ಯೆ",
    surveyNo: "Survey No / ಸರ್ವೇ ಸಂಖ್ಯೆ",
    assignedAt: "Assigned at / ನಿಯೋಜಿಸಿದ ಸಮಯ",
    dueDate: "Due date / ಕೊನೆ ದಿನಾಂಕ",
    assignmentStatus: "Assignment status / ನಿಯೋಜನೆ ಸ್ಥಿತಿ",
    assignmentNotes: "Assignment notes / ನಿಯೋಜನೆ ಟಿಪ್ಪಣಿ",
    surveyType: "Survey type / ಸರ್ವೇ ಪ್ರಕಾರ",
    district: "District / ಜಿಲ್ಲೆ",
    taluka: "Taluka / ತಾಲೂಕು",
    hobli: "Hobli / ಹೋಬಳಿ",
    village: "Village / ಗ್ರಾಮ",
    uploadStatus: "Upload status / ಅಪ್ಲೋಡ್ ಸ್ಥಿತಿ",
    othersNotes: "Others / notes / ಇತರೆ / ಟಿಪ್ಪಣಿ",
    created: "Created / ರಚಿಸಲಾಗಿದೆ",
    updated: "Updated / ನವೀಕರಿಸಲಾಗಿದೆ",
    reviewedAt: "Reviewed at / ಪರಿಶೀಲಿಸಿದ ಸಮಯ",
    reviewedBy: "Reviewed by / ಪರಿಶೀಲಿಸಿದವರು",
    name: "Name / ಹೆಸರು",
    phone: "Phone / ಫೋನ್",
    email: "Email / ಇಮೇಲ್",
    changesRequired: "Changes required / ಬದಲಾವಣೆ ಅಗತ್ಯ",
    statusNote: "Status note / ಸ್ಥಿತಿ ಟಿಪ್ಪಣಿ",
    documentTypesMarked: "Document types marked on upload / ಅಪ್ಲೋಡ್‌ನಲ್ಲಿ ಗುರುತಿಸಿದ ದಾಖಲೆ ಪ್ರಕಾರಗಳು",
    uploaded: "Uploaded / ಅಪ್ಲೋಡ್",
    typeSize: "Type / ಪ್ರಕಾರ",
    noSketchFiles: "No sketch files / ಸ್ಕೆಚ್ ಫೈಲ್‌ಗಳಿಲ್ಲ",
    noAudio: "No audio uploaded / ಆಡಿಯೋ ಅಪ್ಲೋಡ್ ಇಲ್ಲ",
    noCadYet: "No CAD files uploaded yet / ಇನ್ನೂ CAD ಫೈಲ್‌ಗಳಿಲ್ಲ",
    view: "View / ನೋಡಿ",
    download: "Download / ಡೌನ್‌ಲೋಡ್",
    open: "Open / ತೆರೆಯಿರಿ",
    selectFileWarn: "Please select at least one file to upload. / ಅಪ್ಲೋಡ್ ಮಾಡಲು ಕನಿಷ್ಠ ಒಂದು ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ.",
    uploadSuccess: "CAD file(s) uploaded successfully. / CAD ಫೈಲ್(ಗಳು) ಯಶಸ್ವಿಯಾಗಿ ಅಪ್ಲೋಡ್.",
    downloadFail:
      "Download failed. If the file is hosted on a different domain, your browser may block direct download. / ಡೌನ್‌ಲೋಡ್ ವಿಫಲ. ಬೇರೆ ಡೊಮೇನ್‌ನಲ್ಲಿ ಫೈಲ್ ಇದ್ದರೆ ಬ್ರೌಸರ್ ನಿರ್ಬಂಧಿಸಬಹುದು.",
    audioCardTitle: "Audio / ಆಡಿಯೋ",
    audioFile: "Audio file / ಆಡಿಯೋ ಫೈಲ್",
    documentFallback: "Document / ದಾಖಲೆ",
    typeSizeLine: "Type / ಪ್ರಕಾರ: {mime} • Size / ಗಾತ್ರ: {size}",
    audioUnsupported: "Your browser does not support the audio element. / ನಿಮ್ಮ ಬ್ರೌಸರ್ ಆಡಿಯೋ ಬೆಂಬಲಿಸುವುದಿಲ್ಲ.",
    sketchStatus: {
      PENDING: "Pending Review / ಪರಿಶೀಲನೆ ಬಾಕಿ",
      ASSIGNED: "Assigned / ನಿಯೋಜಿಸಲಾಗಿದೆ",
      UNDER_REVIEW: "Under Review / ಪರಿಶೀಲನೆಯಲ್ಲಿ",
      APPROVED: "Approved / ಅನುಮೋದಿತ",
      REJECTED: "Rejected / ತಿರಸ್ಕೃತ",
      IN_PROGRESS: "In Progress / ಪ್ರಗತಿಯಲ್ಲಿ",
      COMPLETED: "Completed / ಪೂರ್ಣಗೊಂಡಿದೆ",
      ON_HOLD: "On Hold / ನಿಲ್ಲಿಸಲಾಗಿದೆ",
      CANCELLED: "Cancelled / ರದ್ದು",
    },
    surveyTypes: {
      joint_flat: "Joint Flat / ಜಂಟಿ ಫ್ಲಾಟ್",
      single_flat: "Single Flat / ಏಕ ಫ್ಲಾಟ್",
    },
    docLabels: {
      moolaTippani: "Moola Tippani / ಮೂಲ ಟಿಪ್ಪಣಿ",
      hissaTippani: "Hissa Tippani / ಹಿಸ್ಸಾ ಟಿಪ್ಪಣಿ",
      atlas: "Atlas / ಅಟ್ಲಾಸ್",
      rrPakkabook: "RR Pakkabook / ಆರ್‌ಆರ್ ಪಕ್ಕಾಬುಕ್",
      kharabu: "Kharabu / ಖರಾಬು",
      is_originaltippani: "Moola Tippani / ಮೂಲ ಟಿಪ್ಪಣಿ",
      is_hissatippani: "Hissa Tippani / ಹಿಸ್ಸಾ ಟಿಪ್ಪಣಿ",
      is_atlas: "Atlas / ಅಟ್ಲಾಸ್",
      is_rrpakkabook: "RR Pakkabook / ಆರ್‌ಆರ್ ಪಕ್ಕಾಬುಕ್",
      is_akarabandu: "Akarabandu / ಅಕರಬಂದು",
      is_kharabuttar: "Kharab Utthar / ಖರಾಬುತ್ತರ",
      is_mulapatra: "Moola Patra / ಮೂಲ ಪತ್ರ",
    },
  },
  profile: {
    pageTitle: "Complete Your Profile / ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ",
    stepLine:
      "Step {c}/6 — Finish required details to continue using the CAD portal. / ಹಂತ {c}/6 — CAD ಪೋರ್ಟಲ್ ಬಳಸಲು ಅಗತ್ಯ ವಿವರಗಳನ್ನು ಪೂರ್ಣಗೊಳಿಸಿ.",
    steps: {
      personal: "Personal / ವೈಯಕ್ತಿಕ",
      kyc: "KYC / KYC",
      bank: "Bank / ಬ್ಯಾಂಕ್",
      upi: "UPI / UPI",
      professional: "Professional / ವೃತ್ತಿಪರ",
      documents: "Documents / ದಾಖಲೆಗಳು",
    },
    firstName: "First Name / ಮೊದಲ ಹೆಸರು",
    lastName: "Last Name / ಕೊನೆಯ ಹೆಸರು",
    phone: "Phone / ಫೋನ್",
    email: "Email / ಇಮೇಲ್",
    address: "Address / ವಿಳಾಸ",
    profilePhoto: "Profile Photo / ಪ್ರೊಫೈಲ್ ಫೋಟೋ",
    aadhaarPhoto: "Aadhaar Photo / ಆಧಾರ್ ಫೋಟೋ",
    accountNumber: "Account Number / ಖಾತೆ ಸಂಖ್ಯೆ",
    accountHolderName: "Account Holder Name / ಖಾತೆದಾರರ ಹೆಸರು",
    bankName: "Bank Name / ಬ್ಯಾಂಕ್ ಹೆಸರು",
    branchName: "Branch Name / ಶಾಖೆಯ ಹೆಸರು",
    ifscCode: "IFSC Code / IFSC ಕೋಡ್",
    upiId: "UPI ID / UPI ಐಡಿ",
    skills: "Skills / ಕೌಶಲ್ಯಗಳು",
    experienceYears: "Experience (Years) / ಅನುಭವ (ವರ್ಷಗಳು)",
    resume: "Resume / ರೆಸ್ಯೂಮೆ",
    addressProof: "Address Proof / ವಿಳಾಸ ಪುರಾವೆ",
    placeholders: {
      firstName: "Enter first name / ಮೊದಲ ಹೆಸರು ನಮೂದಿಸಿ",
      lastName: "Enter last name / ಕೊನೆಯ ಹೆಸರು ನಮೂದಿಸಿ",
      phone: "Enter phone number / ಫೋನ್ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
      address: "Enter address / ವಿಳಾಸ ನಮೂದಿಸಿ",
      accountNumber: "Enter account number / ಖಾತೆ ಸಂಖ್ಯೆ ನಮೂದಿಸಿ",
      accountHolderName: "Enter account holder name / ಖಾತೆದಾರರ ಹೆಸರು",
      bankName: "Enter bank name / ಬ್ಯಾಂಕ್ ಹೆಸರು",
      branchName: "Enter branch name / ಶಾಖೆಯ ಹೆಸರು",
      ifsc: "e.g. SBIN0001234 / ಉದಾ. SBIN0001234",
      upi: "name@bank / ಹೆಸರು@ಬ್ಯಾಂಕ್",
    },
    uploadFile: "Upload file / ಫೈಲ್ ಅಪ್ಲೋಡ್",
    replaceFile: "Replace file / ಫೈಲ್ ಬದಲಾಯಿಸಿ",
    previewFile: "Preview uploaded file / ಅಪ್ಲೋಡ್ ಫೈಲ್ ನೋಡಿ",
    draftSave: "Draft auto-save enabled for this form. / ಈ ಫಾರ್ಮ್‌ಗೆ ಡ್ರಾಫ್ಟ್ ಸ್ವಯಂ ಉಳಿಸುವಿಕೆ.",
    back: "Back / ಹಿಂದೆ",
    next: "Next / ಮುಂದೆ",
    submitProfile: "Submit Profile / ಪ್ರೊಫೈಲ್ ಸಲ್ಲಿಸಿ",
    rules: {
      firstName: "First name is required / ಮೊದಲ ಹೆಸರು ಅಗತ್ಯ",
      lastName: "Last name is required / ಕೊನೆಯ ಹೆಸರು ಅಗತ್ಯ",
      phone: "Phone is required / ಫೋನ್ ಅಗತ್ಯ",
      address: "Address is required / ವಿಳಾಸ ಅಗತ್ಯ",
      aadhaar: "Aadhaar Photo is required / ಆಧಾರ್ ಫೋಟೋ ಅಗತ್ಯ",
      accountNumber: "Account number is required / ಖಾತೆ ಸಂಖ್ಯೆ ಅಗತ್ಯ",
      accountNumberPattern: "Account number must contain numbers only / ಖಾತೆ ಸಂಖ್ಯೆ ಅಂಕೆಗಳ ಮಾತ್ರ",
      accountHolder: "Account holder name is required / ಖಾತೆದಾರರ ಹೆಸರು ಅಗತ್ಯ",
      ifscRequired: "IFSC code is required / IFSC ಅಗತ್ಯ",
      ifscInvalid: "Enter a valid IFSC code / ಮಾನ್ಯ IFSC ನಮೂದಿಸಿ",
      skills: "Select at least one skill / ಕನಿಷ್ಠ ಒಂದು ಕೌಶಲ್ಯ ಆಯ್ಕೆಮಾಡಿ",
      experienceRequired: "Experience is required / ಅನುಭವ ಅಗತ್ಯ",
      experienceRange: "Experience must be between 0 and 50 / ಅನುಭವ 0 ರಿಂದ 50 ರೊಳಗೆ",
      fieldRequired: "{label} is required / {label} ಅಗತ್ಯ",
    },
    fileUploaded: "File uploaded successfully / ಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ಅಪ್ಲೋಡ್",
    uploadFailed: "Upload failed / ಅಪ್ಲೋಡ್ ವಿಫಲ",
    profileUpdateFail: "Failed to update profile / ಪ್ರೊಫೈಲ್ ನವೀಕರಣ ವಿಫಲ",
    profileCompleted: "Profile completed successfully / ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ಪೂರ್ಣಗೊಂಡಿದೆ",
    noUserId: "Failed to update profile / ಪ್ರೊಫೈಲ್ ನವೀಕರಣ ವಿಫಲ",
  },
  wallet: {
    pageTitle: "Wallet / ವಾಲೆಟ್",
    tagPaid: "PAID / ಪಾವತಿಸಿದೆ",
    tagPartial: "PARTIAL / ಭಾಗಶಃ",
    tagPending: "PENDING / ಬಾಕಿ",
    totalEarnings: "Total earnings / ಒಟ್ಟು ಗಳಿಕೆ",
    receivedPayment: "Received payment / ಸ್ವೀಕರಿಸಿದ ಪಾವತಿ",
    pendingPayment: "Pending payment / ಬಾಕಿ ಪಾವತಿ",
    transactionHistory: "Transaction history / ವಹಿವಾಟು ಇತಿಹಾಸ",
    noTransactions: "No transactions yet / ಇನ್ನೂ ವಹಿವಾಟುಗಳಿಲ್ಲ",
    loadFail: "Failed to load wallet / ವಾಲೆಟ್ ಲೋಡ್ ವಿಫಲ",
    loadTxFail: "Failed to load transactions / ವಹಿವಾಟುಗಳ ಲೋಡ್ ವಿಫಲ",
    type: "Type / ಪ್ರಕಾರ",
    revisionNo: "Revision no. / ಪರಿಷ್ಕರಣೆ ಸಂ.",
    totalRs: "Total (₹) / ಒಟ್ಟು (₹)",
    paidRs: "Paid (₹) / ಪಾವತಿಸಿದ (₹)",
    remainingRs: "Remaining (₹) / ಉಳಿದ (₹)",
    status: "Status / ಸ್ಥಿತಿ",
    paidPct: "Paid % / ಪಾವತಿ %",
    date: "Date / ದಿನಾಂಕ",
    amount: "Amount / ಮೊತ್ತ",
    recordedBy: "Recorded by / ದಾಖಲಿಸಿದವರು",
    noPaymentLog: "No payment log entries. / ಪಾವತಿ ಲಾಗ್ ನಮೂದುಗಳಿಲ್ಲ.",
    rangeOf: "{a}-{b} of {t} / {t} ರಲ್ಲಿ {a}-{b}",
  },
};

/** Interpolate `{key}` placeholders in a cadBi string. */
export function cadBiFmt(template, vars = {}) {
  return String(template).replace(/\{(\w+)\}/g, (_, k) =>
    vars[k] != null ? String(vars[k]) : `{${k}}`
  );
}
